### ISSUE TITLE
Investigate on making test classes better for Core library

### ISSUE THREAD

**Issue by kanchanbohra** [SAP/cloud-sdk-currency-conversion#23]
> @kanchanbohra just asked be in a chat that she would like to merge to get some further work going. I think an issue for the following most important point:
> 
> * Check exported const used in test. Often they are created multiple times in local scope or in global scope but only used once
> * Investigate if there isn't an easier way than this test class to do some tests (rather unit than integration tests)
> * Do the minor concrete changes from @marikaner
> 
> @marikaner do you also see other urgent points which need to be tackeled before merging?

Yes, basically my [comment from above](https://github.com/SAP/cloud-sdk-currency-conversion/pull/6#pullrequestreview-581254153) ;)

_Originally posted by @marikaner in https://github.com/SAP/cloud-sdk-currency-conversion/issues/6#issuecomment-773293927_

**Comment by deekshas8** [comment]
This repository is deprecated.
