### ISSUE TITLE
Investigate on calculation and rounding of SingleFixedRateConversionResult

### ISSUE THREAD

**Issue by kanchanbohra** [SAP/cloud-sdk-currency-conversion#27]
I haven't noticed this before, but shouldn't rounding happen here instead of outside? You could use completely different amounts to "build" the result. I think from a safety aspect it makes sense to move this here, right?
```suggestion
// pass only the converted amount
export function buildSingleFixedRateConversionResult(
  convertedAmount: CurrencyAmount
): SingleFixedRateConversionResult {
  return {
    convertedAmount,
    // round the converted amount
    roundedOffConvertedAmount: doTheRounding(convertedAmount)
  };
```

_Originally posted by @marikaner in https://github.com/SAP/cloud-sdk-currency-conversion/pull/6#discussion_r570168659_

**Comment by deekshas8** [comment]
This repository is deprecated.
