### ISSUE TITLE
Follow the style guide and fix the namings of the variables and files- Integration Objects

### ISSUE THREAD

**Issue by vidhyakpai** [SAP/cloud-sdk-currency-conversion#38]
Rename files to be kebap-case and variables (and constants) to be camelCase in the integration-objects. Check the [styleguide](https://github.com/SAP/cloud-sdk-js/blob/main/STYLEGUIDE.md) for details.

This also applies to all other packages, but is most prominent in the integration-objects.

Original PR: #32

**Comment by vidhyakpai** [comment]
Rename the ErrorStatuses util file to ErrorStatus because this is semantically an enum.

**Comment by vidhyakpai** [comment]
Pro tip: Use toThrowErrorMatchingInlineSnapshot. It is helpful when writing the tests, because you don't have to copy the text.

**Comment by vidhyakpai** [comment]
General: I would use the same string in the logger and exception. Best via some variable or method. Doing so you are always aligned.

**Comment by vidhyakpai** [comment]
https://github.com/SAP/cloud-sdk-currency-conversion/pull/29#discussion_r578298393

Go over the modules containing just these constants in RateExtensionConstants and check where and how often they are used. In many cases they can be moved to the smaller methods.

**Comment by vidhyakpai** [comment]
Also note that if you use TypeScript you can not make these errors because the compiler tells you that await on a normal method is not possible.

As I mentioned before could you create an issue for making all the logging,utils,validations typescript files. Then you transpile to JS and require as usual in your srv implementation the JS files. 
https://github.com/SAP/cloud-sdk-currency-conversion/pull/29#discussion_r578296336

**Comment by vidhyakpai** [comment]
the methods validateToCurrencyFactor and validateFromCurrencyFactor and validateExchangeRateValue are the same. Consider making then one method: validateNumberInBounds(value,minMaxValue,errorMessage).
Add then a unit test for the validateNumberInBounds method.

https://github.com/SAP/cloud-sdk-currency-conversion/pull/29#discussion_r578301312

**Comment by vidhyakpai** [comment]
Recommended to make the validatePattern generic in a sense that it tests a pattern for a given value and pattern. It uses then the field name and pattern info to make a nice error message. If your message is about the length than pass it in. But if the method stays like this it is not really usable in other places.

https://github.com/SAP/cloud-sdk-currency-conversion/pull/32#discussion_r578227480

**Comment by vidhyakpai** [comment]
Also this seems dangerous to me. Assume it takes a while to get the audit log or it fails. Then you still export the new AuditLog method. If to get an audit log requires something async I would suggest to define a aysnc method getAuditLog returning a promise containing the AuditLog. This can use the singleton pattern to ensure that just one audit log is returned after the promise is resolved.

https://github.com/SAP/cloud-sdk-currency-conversion/pull/29#discussion_r579099240

**Comment by vidhyakpai** [comment]
please add the argument in the method signature in line 39. The same for all other methods as well. If you expect and argument tell it to the user.

Also please add a issue in the backlog to transform the utils,validations,logging to TypeScript such that we have a more strict control.
https://github.com/SAP/cloud-sdk-currency-conversion/pull/29#discussion_r579095800

**Comment by vidhyakpai** [comment]
This is the exact same code as in the other service. Please avoid code duplication and reuse existing functionality.
For the other services. 

https://github.com/SAP/cloud-sdk-currency-conversion/pull/32#discussion_r579119882

**Comment by FrankEssenberger** [comment]
Could you create seperate issue for the tasks, because this gives a better overview also if other colleagues want to pick an issue. The things I see:
- auditlog async 
- typscript 
- go over constants and see if they are needed
- go over all log/throw combinations and ensure that the same messages are used
- reduce code duplication (collect all point Marika and I mentioned and which are not yet done)

**Comment by deekshas8** [comment]
This repository is deprecated.
